## The Foundation of Machine Learning

#### Course: AI & Machine Learning
#### Week: 1
#### Instructor: Eddie 

### Introduction to Artificial Intelligence & Machine Learning

####  What is Artificial Intelligence (AI)?

Artificial Intelligence is the ability of a computer to behave like a human.

Examples:
- Voice assistants (Siri, Alexa)
- Self-driving cars
- Chatbots

#### What is Machine Learning (ML)?

Machine learning is a part of AI that allows computers to learn from data.

 Instead of programming rules, we give data and let the machine learn patterns.

Example:
- Predict house prices
- Detect spam emails
- Recommend movies

####  AI vs Machine Learning

- AI = Big concept (intelligence)
- ML = Subset of AI (learning from data)

 All ML is AI, but not all AI is ML

#### How Machine Learning Works

1. Collect Data  
2. Clean Data  
3. Train Model  
4. Evaluate Model  
5. Make Predictions  

This is what we will learn step by step

####  Types of Machine Learning

1. Supervised Learning  
   - We have input and correct answers  
   - Example: Predict exam score  

2. Unsupervised Learning  
   - No labels, find patterns  
   - Example: Group customers  

3. Reinforcement Learning  
   - Learn by reward and punishment


####  Tools We Will Use

To build Machine Learning systems, we need tools:

- NumPy → for calculations  
- Pandas → for data handling  
- Scikit-learn → for modeling  

Let's start with Numpy...

## Why Do We Need NumPy?

Before NumPy, Python used lists for handling data.

But lists have problems:
- Slow for large data
- No mathematical operations
- Not memory efficient

### NumPy Solves This:

- Faster computations
- Supports vectorized operations
- Uses less memory
- Backbone of ML libraries like Pandas, Scikit-learn, TensorFlow

NumPy is the engine behind data science.

In [1]:
import numpy as np
import time

"""
lets create two list to pratice why NumPy is the engine behind data science
"""

list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
print("List time:", time.time() - start)



List time: 0.10744428634643555


In [2]:
# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2
print("NumPy time:", time.time() - start)

NumPy time: 0.03882098197937012


In [3]:
# creating numpy array

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

zeros = np.zeros((2,3))
ones = np.ones((2,2))
random = np.random.rand(3,3)

[1 2 3 4]


In [4]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones

array([[1., 1.],
       [1., 1.]])

In [6]:
random

array([[0.71605598, 0.77048057, 0.0051622 ],
       [0.56353917, 0.80355514, 0.16975589],
       [0.26470769, 0.59771915, 0.66846102]])

In [7]:
#array properties
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


In [8]:
#NumPy operations

arr = np.array([1,2,3])

print(arr + 10)
print(arr * 2)
print(arr ** 2)

[11 12 13]
[2 4 6]
[1 4 9]


In [9]:
#Indexing and Slicing
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[1:3])

10
[20 30]


In [16]:
print(arr[-1])

40


In [18]:
# Reshaping Arrays
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
print(arr.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [20]:
# Basic Mathematical Functions
arr = np.array([1,2,3,4])

print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))

2.5
10
4


## Pandas for Data Analysis & Feature Engineering

#### Why Pandas?

NumPy works well with arrays, but real-world data is messy.

Pandas helps us:
- Work with structured data (tables)
- Handle missing values
- Manipulate columns easily
- Prepare data for machine learning.


In [22]:
# Import Libraries
import pandas as pd
import numpy as np

In [23]:
# Creating a DataFrame

data = {
    "Name": ["John", "Mary", "Peter", "Linda"],
    "Age": [28, 34, 29, 42],
    "Gender": ["Male", "Female", "Male", "Female"],
    "Salary": [50000, 60000, 55000, 65000]
}

df = pd.DataFrame(data)
df

,Name,Age,Gender,Salary
0,John,28,Male,50000
1,Mary,34,Female,60000
2,Peter,29,Male,55000
3,Linda,42,Female,65000


In [26]:
df.head(2)


,Name,Age,Gender,Salary
0,John,28,Male,50000
1,Mary,34,Female,60000


In [27]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Gender  4 non-null      object
 3   Salary  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes


In [28]:
df.describe()

,Age,Salary
count,4.000000,4.000000
mean,33.250000,57500.000000
std,6.396614,6454.972244
min,28.000000,50000.000000
25%,28.750000,53750.000000
50%,31.500000,57500.000000
75%,36.000000,61250.000000
max,42.000000,65000.000000


In [29]:
df["Age"]


0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [30]:
df[["Name", "Salary"]]

,Name,Salary
0,John,50000
1,Mary,60000
2,Peter,55000
3,Linda,65000


In [31]:
df[df["Age"] > 30]

,Name,Age,Gender,Salary
1,Mary,34,Female,60000
3,Linda,42,Female,65000


In [32]:
# trying to do little manipulation on our dataset

df["Salary"] * 1.1  


0    55000.0
1    66000.0
2    60500.0
3    71500.0
Name: Salary, dtype: float64

In [33]:

df["Age"].mean()

np.float64(33.25)

In [34]:
df["Salary"].max()

np.int64(65000)

In [35]:
# Working with Categorical Columns

# Encoding
df["Gender_encoded"] = df["Gender"].map({"Male": 0, "Female": 1})
df

,Name,Age,Gender,Salary,Gender_encoded
0,John,28,Male,50000,0
1,Mary,34,Female,60000,1
2,Peter,29,Male,55000,0
3,Linda,42,Female,65000,1


In [36]:
df["Gender"].value_counts()

Gender
Male      2
Female    2
Name: count, dtype: int64

In [38]:
# Handling Missing Values
df.loc[2, "Age"] = None
df

,Name,Age,Gender,Salary,Gender_encoded
0,John,28.0,Male,50000,0
1,Mary,34.0,Female,60000,1
2,Peter,NaN,Male,55000,0
3,Linda,42.0,Female,65000,1


In [39]:
df.isnull().sum()

Name              0
Age               1
Gender            0
Salary            0
Gender_encoded    0
dtype: int64

In [40]:
df["Age"].fillna(df["Age"].mean(), inplace=True)
df

/tmp/ipykernel_738/3445616279.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)


,Name,Age,Gender,Salary,Gender_encoded
0,John,28.000000,Male,50000,0
1,Mary,34.000000,Female,60000,1
2,Peter,34.666667,Male,55000,0
3,Linda,42.000000,Female,65000,1


In [41]:
df

,Name,Age,Gender,Salary,Gender_encoded
0,John,28.000000,Male,50000,0
1,Mary,34.000000,Female,60000,1
2,Peter,34.666667,Male,55000,0
3,Linda,42.000000,Female,65000,1


In [42]:
#Create New Features

df["Age_Group"] = df["Age"].apply(lambda x: "Young" if x < 30 else "Adult")

df["Salary_Level"] = df["Salary"].apply(lambda x: "High" if x > 55000 else "Low")

df

,Name,Age,Gender,Salary,Gender_encoded,Age_Group,Salary_Level
0,John,28.000000,Male,50000,0,Young,Low
1,Mary,34.000000,Female,60000,1,Adult,High
2,Peter,34.666667,Male,55000,0,Adult,Low
3,Linda,42.000000,Female,65000,1,Adult,High


NOTE: the code below is doing same thing as the lambda function 

In [ ]:
def get_age_group(age):
    if age < 30:
        return "Young"
    else:
        return "Adult"

def get_salary_level(salary):
    if salary > 55000:
        return "High"
    else:
        return "Low"

df["Age_Group"] = df["Age"].apply(get_age_group)
df["Salary_Level"] = df["Salary"].apply(get_salary_level)

df

In [43]:
# Combine Features
df["Profile"] = df["Gender"] + "_" + df["Age_Group"]

In [44]:
df

,Name,Age,Gender,Salary,Gender_encoded,Age_Group,Salary_Level,Profile
0,John,28.000000,Male,50000,0,Young,Low,Male_Young
1,Mary,34.000000,Female,60000,1,Adult,High,Female_Adult
2,Peter,34.666667,Male,55000,0,Adult,Low,Male_Adult
3,Linda,42.000000,Female,65000,1,Adult,High,Female_Adult


In [45]:
# Sorting & Grouping
df.sort_values(by="Salary", ascending=False)



,Name,Age,Gender,Salary,Gender_encoded,Age_Group,Salary_Level,Profile
3,Linda,42.000000,Female,65000,1,Adult,High,Female_Adult
1,Mary,34.000000,Female,60000,1,Adult,High,Female_Adult
2,Peter,34.666667,Male,55000,0,Adult,Low,Male_Adult
0,John,28.000000,Male,50000,0,Young,Low,Male_Young


In [46]:
df.groupby("Gender")["Salary"].mean()

Gender
Female    62500.0
Male      52500.0
Name: Salary, dtype: float64

#### What is Machine Learning?

Machine Learning is teaching a computer to learn patterns from data and make predictions.

 Example:
- Predict house price
- Predict if a student will pass

let's demostrate Machine Learning

In [47]:
# import libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

#### Load Dataset (Simple & Beginner-Friendly)

We’ll use Breast Cancer dataset (built into sklearn)

In [48]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

# Convert to DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = data.target

df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0


In [49]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [50]:
df.describe()


,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000


In [51]:
df["target"].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [52]:
#Feature & Target Selection
X = df.drop("target", axis=1)  # Features
y = df["target"]              # Target

In [53]:
X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [54]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

In [55]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [56]:
#Train Model
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,5000
,multi_class,'deprecated'


In [57]:
# Make Predictions
y_pred = model.predict(X_test)

In [58]:
#Evaluate Model
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.956140350877193
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [59]:

sample = X_test.iloc[0].values.reshape(1, -1)

prediction = model.predict(sample)

print("Prediction:", prediction)

Prediction: [1]


/home/eddie/python-systems-lab/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


## The End!!!